spring.application.name=pokestrategy

spring.datasource.url=jdbc:mysql://localhost:3306/pokestrategy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=pokestrategy
spring.datasource.password=pokestrategy123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
